Proyecto_Indicadores/Models/Catalogo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Proyecto_Indicadores.Models
{
    public class Catalogo
    {
        public int IdCatalogo { get; set; }
        public String Prefijo { get; set; }
        public String Descripcion { get; set; }
    }
}

Proyecto_Indicadores/Models/Estado.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Proyecto_Indicadores.Models
{
    public class Estado
    {
        public int IdEstado { get; set; }
        public String Sigla { get; set; }
        public String Descripcion { get; set; }
    }
}

Proyecto_Indicadores/Models/Indicador.cs
namespace Proyecto_Indicadores.Models
{
    public class Indicador
    {
        public int IdIndicador { get; set; }
        public int IdCatalogo { get; set; }
        public int IdUnidad { get; set; }
        public int IdPeriodo { get; set; }
        public int IdEstado { get; set; }
    }

    public class TablaIndicador {

        public int IdIndicador { get; set; }
        public string Catalogo { get; set; }
        public string Estado { get; set; }
        public string Perido { get; set; }
        public string Moneda { get; set; }
        public string Metadata { get; set; }
    }

}

Proyecto_Indicadores/Models/Periodo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Proyecto_Indicadores.Models
{
    public class Periodo
    {
        public int IdPeriodo { get; set; }
        public Char Siglas { get; set; }
    }
}

Proyecto_Indicadores/Models/UnidadMedida.cs
namespace Proyecto_Indicadores.Models
{
    public class UnidadMedida
    {
        public int IdUnidad { get; set; }

        public string Siglas { get; set; }

        public string Descripcion { get; set; }

    }
}

Proyecto_Indicadores/Controllers/IndicadorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Data;
using System.IO;
using System.Xml.Serialization;
using Proyecto_Indicadores.Models;
using Proyecto_Indicadores.Models.BaseDatos;
using System.Data.Entity;

namespace IndicadoresBancarios.Controllers
{
    public class IndicadorController : Controller
    {
        private readonly BD_Indicadores contexto = new BD_Indicadores();

        public ActionResult CrearIndicador()
        {
            CargarDropDown objDatosDropDownList = new CargarDropDown()
            {
                listaCatalogos = new SelectList(contexto.TB_Catalogo.Select(x => x), "IdCatalogo", "Prefijo"),
                listaEstados = new SelectList(contexto.TB_Estado.Select(x => x), "IdEstado", "Sigla"),
                listaUnidades = new SelectList(contexto.TB_UnidadMedida.Select(x => x), "IdUnidad", "Siglas"),
                listaPeriodos = new SelectList(contexto.TB_Periodo.Select(x => x), "IdPeriodo", "Siglas")
            };
            return View(objDatosDropDownList);
        }

        public ActionResult CrearIndicador_Posvalores()
        {
            var resultado = (from c in contexto.TB_Posvalor
                             join a in contexto.TB_Metadata
                             on c.IdMetadata equals a.IdMetadata
                             select new Posvalor
                             {
                                 IdPosvalor = c.IdPosvalor,
                                 Valor = a.Prefijo + c.Valor,
                                 Descripcion = a.Nombre + ": " + c.Descripcion
                             }).ToList();
            return View(resultado);
        }

        public ActionResult EditarIndicador(int idIndicador)
        {
            var indicador = contexto.TB_Indicador.Where(x => x.IdIndicador == idIndicador).FirstOrDefault();
            CargarDropDown objDatosDropDownList = new CargarDropDown()
            {
                listaCatalogos = new SelectList(contexto.TB_Catalogo.Select(x => x), "IdCatalogo", "Prefijo", indicador.IdCatalogo),
                listaEstados = new SelectList(contexto.TB_Estado.Select(x => x), "IdEstado", "Sigla", indicador.IdEstado),
                listaPeriodos = new SelectList(contexto.TB_Periodo.Select(x => x), "IdPeriodo", "Siglas", indicador.IdPeriodo),
                listaUnidades = new SelectList(contexto.TB_UnidadMedida.Select(x => x), "IdUnidad", "Siglas", indicador.IdUnidad)

            };
            return View("CrearIndicador", objDatosDropDownList);
        }

        [HttpPost]
        public ActionResult GetIds(string[] arrValores)
        {
            TB_Indicador objIndicador = new TB_Indicador();

            string Prefijo = arrValores[0];
            string Estado = arrValores[1];
            string Periodo = arrValores[2];
            string UnidadMedida = arrValores[3];

            var catalogo = contexto.TB_Catalogo.Where(x => x.Prefijo == Prefijo).FirstOrDefault();
            var estado = contexto.TB_Estado.Where(x => x.Sigla == Estado).FirstOrDefault();
            var periodo = contexto.TB_Periodo.Where(x => x.Siglas == Periodo).FirstOrDefault();
            var unidad = contexto.TB_UnidadMedida.Where(x => x.Siglas == UnidadMedida).FirstOrDefault();

            objIndicador.IdCatalogo = catalogo.IdCatalogo;
            objIndicador.IdEstado = estado.IdEstado;
            objIndicador.IdPeriodo = periodo.IdPeriodo;
            objIndicador.IdUnidad = unidad.IdUnidad;

            GuardarCambiosIndicador(objIndicador);
            GuardarIndicadorPosvalor(objIndicador.IdIndicador, arrValores);

            return View(arrValores);
        }

        public ActionResult ListarIndicadores()
        {
            List<TablaIndicador> listaindicadores = Listar();
            return View(listaindicadores);
        }

        private List<TablaIndicador> Listar()
        {
            List<TablaIndicador> listaIndicadores = new List<TablaIndicador>();

            var consultaIndicadores = contexto.V_SelectIndicadores.Where(x => x.Id == x.Id);
            var consultaMetadata = contexto.V_SelectMetadata.Where(x => x.Indicador == x.Indicador);

            DataTable TMetadatas = new DataTable();
            TMetadatas.Columns.Add("Id");
            TMetadatas.Columns.Add("Metadata");
            TMetadatas.Columns.Add("PosValor");

            foreach (var m in consultaMetadata)
            {
                DataRow row = TMetadatas.NewRow();
                row["Id"] = m.Indicador;
                row["Metadata"] = m.Metadata;
                row["PosValor"] = m.Posvalor;

                TMetadatas.Rows.Add(row);
            }

            foreach (var t in consultaIndicadores)
            {
                TablaIndicador objtablaIndicador = new TablaIndicador
                {
                    IdIndicador = t.Id,
                    Catalogo = t.Prefijo,
                    Estado = t.Estado,
                    Perido = t.Periodo,
                    Moneda = t.Moneda
                };

                foreach (DataRow row in TMetadatas.Rows)
                {
                    if (t.Id == Convert.ToInt32(row["Id"]))
                    {
                        objtablaIndicador.Metadata += row["Metadata"].ToString() + row["PosValor"].ToString() + ".";
                    }
                }
                objtablaIndicador.Metadata = objtablaIndicador.Metadata.Substring(0, (objtablaIndicador.Metadata.Length - 1));

                listaIndicadores.Add(objtablaIndicador);
                objtablaIndicador = null;
            }

            return listaIndicadores;
        }

        private void GuardarIndicadorPosvalor(int idIndicador, string[] arrValores)
        {
            for (int i = 4; i < arrValores.Length; i++)
            {
                string valor = arrValores[i].Remove(0, 3);
                var posvalor = contexto.TB_Posvalor.Where(x => x.Valor == valor).FirstOrDefault();

                TB_IndicadorPosvalor objIndiPosvalor = new TB_IndicadorPosvalor()
                {
                    IdIndicador = idIndicador,
                    IdPosvalor = posvalor.IdPosvalor,
                    Orden = i - 3
                };
                contexto.TB_IndicadorPosvalor.Add(objIndiPosvalor);
                contexto.SaveChanges();
            }
        }

        public ActionResult EliminarIndicador(int idIndicador)
        {
            try
            {
                foreach (var x in contexto.TB_IndicadorPosvalor)
                {
                    if (x.IdIndicador == idIndicador)
                    {
                        contexto.TB_IndicadorPosvalor.Remove(x);
                    }
                }
                contexto.SaveChanges();

                var indicador = contexto.TB_Indicador.Where(x => x.IdIndicador == idIndicador).FirstOrDefault();
                contexto.TB_Indicador.Remove(indicador);
                contexto.SaveChanges();
            }
            catch (Exception e)
            {
                ViewBag.Msg = string.Format("Ocurrio un error al eliminar el archivo, compruebe el listado de nuevo") + e;
            }
            var list = Listar();
            return View("ListarIndicadores", (object)list);
        }

        public ActionResult ExportarExcel()
        {
            var stream = new MemoryStream();
            var serialicer = new XmlSerializer(typeof(List<TablaIndicador>));

            List<TablaIndicador> datos = Listar();

            serialicer.Serialize(stream, datos);
            stream.Position = 0;
            return File(stream, "application/vnd.ms-excel", "Unidades de Medida.xls");
        }

        private void GuardarCambiosIndicador(TB_Indicador objIndicador)
        {
            contexto.TB_Indicador.Add(objIndicador);
            contexto.SaveChanges();
        }
    }
}

Proyecto_Indicadores/Controllers/UnidadMedidaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proyecto_Indicadores.Models.BaseDatos;
using Proyecto_Indicadores.Models;
using System.Xml.Serialization;
using System.IO;
using System.Text.RegularExpressions;
using System.Data;


namespace Proyecto_Indicadores.Controllers
{
    public class UnidadMedidaController : Controller
    {

        public List<UnidadMedida> ListUnidadMedida()
        {
            BD_Indicadores consulta = new BD_Indicadores();
            var resultado = (from c in consulta.TB_UnidadMedida
                             select new UnidadMedida
                             {
                                 IdUnidad = c.IdUnidad,
                                 Siglas = c.Siglas,
                                 Descripcion = c.Descripcion
                             }).ToList();

            return (resultado);
        }

        public ActionResult GetDataPreEdit(int idUnidad)
        {
            BD_Indicadores consulta = new BD_Indicadores();
            var consultaUnidad = (from u in consulta.TB_UnidadMedida
                                  where u.IdUnidad == idUnidad
                                  select new UnidadMedida
                                  {
                                      IdUnidad = idUnidad,
                                      Siglas = u.Siglas,
                                      Descripcion = u.Descripcion
                                  }).FirstOrDefault();


            return View("CrearUnidadMedida", consultaUnidad);
        }

        public void EditarUnidadMedida(UnidadMedida objUnidadMedida)
        {
            Regex val = new Regex(@"^[a-zA-Z]*$");
            if (val.IsMatch(objUnidadMedida.Siglas))
            {
                using (BD_Indicadores update = new BD_Indicadores())
                {
                    TB_UnidadMedida unidad = update.TB_UnidadMedida.Single(u => u.IdUnidad == objUnidadMedida.IdUnidad);
                    unidad.Siglas = objUnidadMedida.Siglas;
                    unidad.Descripcion = objUnidadMedida.Descripcion;
                    update.SaveChanges();
                    update.Dispose();
                }
            }
            else
            {
                ViewBag.Message = string.Format("Solo se admiten letras");
            }
        }

        [HttpPost]
        public JsonResult GuardarUnidadMedida(UnidadMedida objUnidadMedida)
        {
            string result = string.Empty;
            if (objUnidadMedida != null)
            {
                Regex val = new Regex(@"^[a-zA-Z]*$");
                if (val.IsMatch(objUnidadMedida.Siglas))
                {
                    using (BD_Indicadores contexto = new BD_Indicadores())
                    {
                        TB_UnidadMedida unidad = new TB_UnidadMedida
                        {
                            Siglas = objUnidadMedida.Siglas,
                            Descripcion = objUnidadMedida.Descripcion
                        };

                        contexto.TB_UnidadMedida.Add(unidad);
                        contexto.SaveChanges();
                        result = "Saved";
                    }
                }
                else
                {
                    ViewBag.Message = string.Format("Solo se admiten letras");
                }
            }
            return Json(result);
        }

        public ActionResult EliminarUnidadMedida(int idUnidad)
        {
            try
            {
                if (idUnidad > 0)
                {
                    using (BD_Indicadores delete = new BD_Indicadores())
                    {
                        TB_UnidadMedida unidad = (from u in delete.TB_UnidadMedida
                                                  where u.IdUnidad == idUnidad
                                                  select u).FirstOrDefault();
                        if (unidad != null)
                        {
                            delete.TB_UnidadMedida.Remove(unidad);
                            delete.SaveChanges();
                            ViewBag.Msg = string.Format("Registro eliminado correctamente!");
                        }
                    }
                }
            }
            catch (Exception)
            {

                ViewBag.Msg = string.Format("Ocurrio un error al eliminar el archivo, compruebe el listado de nuevo");
            }
            var resultado = ListUnidadMedida();

            return View("UnidadMedida", resultado);
        }

        public ActionResult ExportarExcel()
        {

            BD_Indicadores consultar = new BD_Indicadores();

            var stream = new MemoryStream();
            var serialicer = new XmlSerializer(typeof(List<UnidadMedida>));

            List<UnidadMedida> datos = (from u in consultar.TB_UnidadMedida
                                        select new UnidadMedida
                                        {
                                            IdUnidad = u.IdUnidad,
                                            Siglas = u.Siglas,
                                            Descripcion = u.Descripcion
                                        }).ToList();

            serialicer.Serialize(stream, datos);
            stream.Position = 0;

            return File(stream, "application/vnd.ms-excel", "Unidades de Medida.xls");
        }

        public ActionResult ImportXmlData(HttpPostedFileBase xmlFile)
        {
            try
            {
                if (xmlFile != null && xmlFile.ContentLength > 0)
                {
                    var nombreArchivo = Path.GetFileName(xmlFile.FileName);
                    var path = Path.Combine(Server.MapPath("~/App_Data/"), nombreArchivo);
                    xmlFile.SaveAs(path);

                    DataSet ds = new DataSet();
                    ds.ReadXml(path);

                    var _unidadMedida = new List<TB_UnidadMedida>();
                    _unidadMedida = (from rows in ds.Tables[0].AsEnumerable()
                                     select new TB_UnidadMedida
                                     {
                                         Siglas = rows[0].ToString(),
                                         Descripcion = rows[1].ToString(),
                                     }).ToList();

                    using (BD_Indicadores insert = new BD_Indicadores())
                    {
                        foreach (TB_UnidadMedida unidad in _unidadMedida)
                        {
                            insert.TB_UnidadMedida.Add(unidad);
                            insert.SaveChanges();
                            ViewBag.Msg = "Archivo cargado correctamente";
                        }
                    }

                }

            }
            catch (Exception)
            {
                ViewBag.Msg = string.Format("Ocurrio un error al intentar cargar el archivo seleccionado."); ;
            }
            var lista = ListUnidadMedida();
            return View("UnidadMedida", lista);
        }


        public ActionResult UnidadMedida()
        {
            var resultado = ListUnidadMedida();
            return View(resultado);
        }

        public ActionResult CrearUnidadMedida()
        {
            return View();
        }


    }
}

Proyecto_Indicadores/Views/Indicador/Catalogo.cshtml
@model Proyecto_Indicadores.Models.BaseDatos.TB_Catalogo

@{
    ViewBag.Title = "CatalogoConsulta";
    Layout = null;
}


<div class="form-group">
    @Html.LabelFor(model => model.IdCatalogo, "Catalogo")
    <div class="col-md-10">
        @Html.DropDownListFor(m => m.IdCatalogo, (SelectList)ViewBag.ddlCatalogo)
        @Html.ValidationMessageFor(model => model.IdCatalogo, "", new { @class = "text-danger" })
    </div>
</div>

Proyecto_Indicadores/Views/Indicador/CrearIndicador.cshtml
@using Proyecto_Indicadores.Models;

@model CargarDropDown

@{
    ViewBag.Title = "Crear Indicador";
    Layout = "~/Views/Shared/_IndicadoresLayout.cshtml";
    string[] arrSeleccion = new string[4];
}

<script type="text/javascript">

    function vistaPrevia() {
        document.getElementById("lblVistaPrevia").textContent =
                  document.getElementById("ddlCatalogo").options[document.getElementById("ddlCatalogo").selectedIndex].text +
            "." + document.getElementById("ddlEstado").options[document.getElementById("ddlEstado").selectedIndex].text +
            "." + document.getElementById("ddlPeriodo").options[document.getElementById("ddlPeriodo").selectedIndex].text +
            "." + document.getElementById("ddlUnidad").options[document.getElementById("ddlUnidad").selectedIndex].text;
        guardarSeleccion();
    }

    function guardarSeleccion() {
        document.cookie = "seleccion =" + document.getElementById("lblVistaPrevia").textContent + ";" + Date(0, 0, 0, 2, 0, 0, 0);
    }
</script>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div id="DivCuerpo" class="form-horizontal" style="margin-left:15%">
        <h1 class="Titulos" style="text-align:center"> Crear Indicador</h1>

        <div class="card" style="background-color: #ededed; width:70%; height: 50%; margin-left: 15%">

            <div class="card-body">

                <label> Para crear el indicador seleccione por favor los valores: Catalogo, Estado, Periodicidad y Unidad de Medida respectivamente.</label>

                <div style="float:left; margin-left:20%; margin-top: 2%">


                    @Html.DropDownList("Catalogo", Model.listaCatalogos, new { @id = "ddlCatalogo", @class = "dropdown", @onchange = "vistaPrevia()" })
                </div>

                <div style="float:left; margin-left:15px; margin-top: 2%">
                    @Html.DropDownList("Estado", Model.listaEstados, new { @id = "ddlEstado", @class = "dropdown", @onchange = "vistaPrevia()" })
                </div>

                <div style="float:left; margin-left:15px; margin-top: 2%">
                    @Html.DropDownList("Periodo", Model.listaPeriodos, new { @id = "ddlPeriodo", @class = "dropdown", @onchange = "vistaPrevia()" })
                </div>

                <div style="float:left; margin-left:15px; margin-top: 2%">
                    @Html.DropDownList("Unidad", Model.listaUnidades, new { @id = "ddlUnidad", @class = "dropdown", @onchange = "vistaPrevia()" })
                </div>

                <input type="submit" name="Guardar" value="Continuar y agregar Pos Valores" class="btn btn-primary" style="margin-top:50px; margin-left: 30%"
                       onclick="guardarSeleccion()"
                       formaction="@Url.Action("CrearIndicador_Posvalores", "Indicador", arrSeleccion)"
                       formmethod="post" />
            </div>
        </div>
        <br />
        <div>
            <label class="text-black-50" style="margin-left: 35%">Vista Previa:</label>
            <label class="text-black-50" id="lblVistaPrevia">
                <script>
                    vistaPrevia();
                </script>
            </label>

        </div>

    </div>
}

Proyecto_Indicadores/Views/Indicador/CrearIndicador_Metadata.cshtml
@using Proyecto_Indicadores.Models;
@using GridMvc.Html;

@model  List<MostrarIndicador>

@{
    ViewBag.Title = "Crear Indicador";
    Layout = "~/Views/Shared/_IndicadoresLayout.cshtml";
}

<div class="row container-fluid">

    <div class="col-sm-12 col-md-7" style="height:300px">
        <div class="d-flex row justify-content-center align-items-center" style="height:100%">
            <form>
                <div class="form-group">
                    <label for="txtCatagolo" class="my-label">Cuenta Catalogo</label>
                    <input type="text" id="txtCatagolo" placeholder="Nueva Cuenta Catalogo" class="form-control" maxlength="15" />
                </div>
            </form>

            <div class="col-12 align-self-end  text-center">
                <label class="my-label">Vista Previa:</label>
                <label class="my-label" id="lblVistaPrevia"></label>
            </div>
        </div>
    </div>

    <div class="col-sm-12  col-md-5" style="height:300px">
        <h4 class="text-black-50">Lista de Cuentas Catalogo</h4>

        @Html.Grid(Model).Columns(column =>
   {
       column.Add(model => model.metadata).Titled("Posvalor").Sortable(true).Filterable(true);}).WithPaging(5).Sortable(true).Selectable(true)
    </div>
</div>

<div class="row container-fluid align-bottom justify-content-end" style="margin-top:20px">
    <div class="my-btn">
        <input type="button" value="Cancelar" class="btn btn-outline-danger">
    </div>
    <div class="my-btn">
        <input type="button" value="Siguiente" class="btn btn-outline-success">
    </div>
</div>

Proyecto_Indicadores/Views/Indicador/CrearIndicador_Posvalores.cshtml
@using GridMvc.Html;

@model List<Proyecto_Indicadores.Models.Posvalor>

@{
    ViewBag.Title = "Crear Indicador";
    Layout = "~/Views/Shared/_IndicadoresLayout.cshtml";
}

<script type="text/javascript">

    function getId() {

        var getCookie = ";" + document.cookie;
        var indicador = getCookie.substring(11, getCookie.length);

        $('input:checked').each(function () {
            var row = $(this).closest('tr');
            var valor = row.children('td').eq(2).text();

            if (valor != "") {

                indicador += "." + valor;
                document.getElementById("lblVistaPrevia").textContent = indicador;
            }
            else {
                document.getElementById("lblVistaPrevia").textContent = indicador;
            }
        })
    };

    function getIndicador() {

        var vistaPrevia = document.getElementById("lblVistaPrevia").textContent;
        var arrValores = vistaPrevia.split('.');

        GuardarIndicador(arrValores);
    }

    function GuardarIndicador(arrValores) {

        $.ajax({
            type: 'POST',
            url: '/Indicador/GetIds',
            contentType: 'application/json; charset=utf-8',
            data: JSON.stringify(arrValores),
            dataType: 'application/json',
            async: true,
            processData: false,
            cache: false,
            success: function (data) {
                alert('Se ha guardado el nuevo registro.');
            },
            error: function (jq, status, message) {
                alert('Ocurrió un error al intentar guardar el registro');
            }
        });

    }
</script>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
<div id="DivCuerpo" class="form-horizontal" style="width:95%">

    <div class="row container-fluid">

        <div class="col-sm-12 col-md-7 card-body" style="width:100%">

            <div class="d-flex row justify-content-start card" style="background-color: #ededed; width:100%; height:350px">

                    <label class="my-label" style="margin-left:2%; margin-top: 15px">Vista Previa</label>

                    <br style="visibility:hidden" />



                    <textarea id="lblVistaPrevia" class="my-label" style="margin-left: 2%; width: 75%; height: 45%">

                        @if (Request.Cookies["seleccion"] != null)
                        {
                            @Request.Cookies["seleccion"].Value;
                        }
                    </textarea>

                @using (Html.BeginForm(FormMethod.Post))
                {
                        <input style="margin-top: 5%; margin-left:30%; width:200px" type="button" id="btnGuardar" value="Guardar Indicador" onclick="getIndicador()" class="btn btn-primary" />
                }
            </div>
        </div>

        <div class="col-sm-12  col-md-5" style="height:100px">
            <h4 class="text-black-50">Posvalores</h4>

            <div style="overflow: scroll; height: 400px">

                @Html.Grid(Model).Columns(column =>
           {
               column.Add().Encoded(false).Sanitized(false)
                   .RenderValueAs(o => Html.CheckBox("Agregar", new { @onclick = "getId()", @id = "cBox_Seleccionar" }));

               column.Add(model => model.IdPosvalor, true).Sortable(true).Filterable(true);
               column.Add(model => model.Valor).Titled("Valor").Sortable(true).Filterable(true);
               column.Add(model => model.Descripcion).Titled("Descripción").Sortable(true).Filterable(true);
               column.Add(model => model.IdMetadata, true);
           }).Sortable(true).Named("Posvalores").Selectable(true);

            </div>
           
        </div>
    </div>


</div>

    }

Proyecto_Indicadores/Views/Indicador/CrearIndicador_UnidadPeriodoEstado.cshtml
@using Proyecto_Indicadores.Models;
@using GridMvc.Html;

@model CargarDropDownList

@{
    ViewBag.Title = "Crear Indicador";
    Layout = "~/Views/Shared/_IndicadoresLayout.cshtml";
}

<div class="row container-fluid">

    <div class="col-md">
        <div class="d-flex row justify-content-center" style="height:300px">


            <div class="col-3 justify-content-center align-content-center">
                <label class="my-label">Estado</label>
                <br />
                @Html.DropDownList("Estado", Model.listaEstados, "Elegir Estado", new { @id = "ddlEstado", @class = "dropdown" })
            </div>
            <div class="col-3">
                <label class="my-label">Periodo</label>
                <br />
                @Html.DropDownList("Periodo", Model.listaPeriodos, "Elegir Periodo", new { @id = "ddlPeriodo", @class = "btn btn-outline-secondary" })
            </div>
            <div class="col-3 text-center">
                <label class="my-label">Unidad de Medida</label>
                <br />
                @Html.DropDownList("Unidad de Medida", Model.listaUnidades, "Elegir Unidad de Medida", new { @id = "ddlUnidad", @class = "btn btn-outline-primary" })
            </div>





            <div class="col-12 align-self-end text-center">
                <label class="my-label">Vista Previa:</label>
                <label class="my-label" id="lblVistaPrevia"></label>
            </div>
        </div>
    </div>

</div>

<div class="row container-fluid align-bottom justify-content-end">
    <div class="my-btn">
        <input type="button" value="Atras" class="btn btn-outline-info" />
    </div>
    <div class="my-btn">
        <input type="button" value="Siguiente" class="btn btn-outline-success" />
    </div>
</div>

Proyecto_Indicadores/Views/Indicador/ListarIndicadores.cshtml
@using GridMvc.Html
@using Proyecto_Indicadores.Models;
@model List<TablaIndicador> 

@{
    ViewBag.Title = "Indicadores";
    Layout = "~/Views/Shared/_IndicadoresLayout.cshtml";
}


<h1 class="Titulos">Registros: @ViewBag.Title</h1>

<div class="container-fluid row justify-content-center">
    <div class="col">
        
        <div>
            <nav class="navbar navbar-light" style="margin-left:-2%">
                <ul class="nav justify-content-center">
                    <li class="nav-item">@Html.ActionLink("Crear Nuevo", "CrearIndicador")</li>
                    <li class="nav-item" style="padding-left: 30px">@Html.ActionLink("Exportar", "ExportarExcel", null, null)</li>
                </ul>
            </nav>
        </div>

        @Html.Grid(Model).Columns(Columns =>
   {
       Columns.Add(c => c.IdIndicador).Titled("IdIndicador").Filterable(true);
       Columns.Add(c => c.Catalogo).Titled("C.Catalogo").Filterable(true);
       Columns.Add(c => c.Estado).Titled("Estado").Filterable(true);
       Columns.Add(c => c.Perido).Titled("Periodo").Filterable(true);
       Columns.Add(c => c.Moneda).Titled("Unidad Medida").Filterable(true);
       Columns.Add(c => c.Metadata).Titled("Metadata").Filterable(true);
       Columns.Add()
           .Encoded(false)
           .Sanitized(false)
           .RenderValueAs(o => Html.ActionLink("Eliminar", "EliminarIndicador", "Indicador", new { idIndicador = o.
        IdIndicador }, null));
   }).WithPaging(5).Sortable(true)
    </div>
</div>